config/routes.rb
Rails.application.routes.draw do
  get "pages/about"
  root to: "home#index"
  devise_for :users

  resources :users do
    patch :toggle_completed_tasks
  end

  resources :tasks do
    member do
      post :toggle_today
      get :edit_modal
    end
  end

  resources :comments, only: [ :index, :new, :create, :destroy ]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :parent, class_name: "Comment", optional: true
  has_many :replies, class_name: "Comment", foreign_key: "parent_id", dependent: :destroy

  validates :content, presence: true

  scope :root_comments, -> { where(parent_id: nil).order(created_at: :desc).includes(:user) }
  scope :parents, -> { where(parent_id: nil) }

  def self.build_by_user(user, params)
    user.comments.build(params)
  end

  def self.find_by_user(user, id)
    user.comments.find(id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @comments = Comment.parents.includes(:user, :replies).order(created_at: :desc)
    @comment = Comment.new
  end

  def new
    @comment = Comment.new(parent_id: params[:parent_id])
  end

  def create
    @comment = Comment.build_by_user(current_user, comment_params)
    if @comment.save
      redirect_to comments_path
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find_by_user(current_user, params[:id])
    @comment.destroy
    redirect_to comments_path
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :parent_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/index.html.erb
<div class="comment-page-container">
  <div class="comment-wrapper">
    <h2 class="main-title">Comments</h2>
    <i class="fa-solid fa-pen"></i>
    <%= link_to "ユーザー名の変更", edit_user_path(current_user), class: "no-decolation-link mini-font-size" %>

    <hr>

    <% if @comments.empty? %>
      <p class="no-comment-text">no comments...</p>
    <% else %>
      <% @comments.each do |comment| %>
        <div class="comments-list">
          <div class="comment-header">
            <strong><%= comment.user.name %></strong>

            <%= link_to new_comment_path(parent_id: comment.id), class: "reply-link" do %>
              <i class="fa-regular fa-message" style="color: #9e9e9e; margin-right: 4px;"></i>
            <% end %>

            <% if comment.user == current_user %>
              <%= button_to comment_path(comment), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "icon-button" do %>
                  <i class="fa-solid fa-trash-can" style="color: #9e9e9e;"></i>
                <% end %>
            <% end %>
          </div>

          <p><%= comment.content %></p>

          <% comment.replies.each do |reply| %>
            <div class="reply">
              <strong><%= reply.user.name %></strong>
              <p><%= reply.content %></p>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>

  <%= link_to new_comment_path, class: "floating-button" do %>
    <i class="fa-solid fa-plus fa-3x" style="color: #ffffff; position: relative; top: 3px;"></i>
  <% end %>
</div>

app/views/comments/new.html.erb
<div class="comment-wrapper">
  <h2 class="main-title"><%= @comment.parent_id.present? ? '返信を書く' : '投稿' %></h2>
  <hr>

  <div class="comment-container">
    <%= form_with model: @comment, url: comments_path, local: true do |f| %>
      <%= f.hidden_field :parent_id %>

      <%= f.text_area :content, rows: 5, class: "form-textarea comment-form"  %>
      <%= f.submit '投稿', class: "comment-submit-button" %>
    <% end %>

    <div style="margin-top: 1rem;">
      <i class="fa-solid fa-chevron-left" style="color: #9e9e9e;"></i>
      <%= link_to 'back', comments_path, class: "no-decolation-link" %>
    </div>
  </div>
</div>