config/routes.rb
Rails.application.routes.draw do
  get "pages/about"
  root to: "home#index"
  devise_for :users

  resources :users do
    patch :toggle_completed_tasks
  end

  resources :tasks do
    member do
      post :toggle_today
      get :edit_modal
    end
  end

  resources :comments, only: [ :index, :new, :create, :destroy ]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>やるる</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# --- Icons --- %>
    <link rel="icon" href="<%= asset_path('other.png') %>" type="image/png" />

    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css", rel: "stylesheet" %>

    <%# --- Stylesheets --- %>
    <%= stylesheet_link_tag :app %>

    <%# --- JavaScript (Chartkick & Chart.js) --- %>
    <%= javascript_include_tag "chartkick" %>
    <%= javascript_include_tag "Chart.bundle" %>

    <%# --- Optional: PWA manifest (Uncomment if used in config/routes.rb) --- %>
    <%# tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <%= javascript_importmap_tags %>

    <%= yield :head %>
  </head>

  <body class="<%= "#{controller_name}-#{action_name}" %>">
    <div class="header">
      <%= link_to "HOME", tasks_path(current_user), class: "btn home-btn" %>
      
      <% unless controller_name == "home" && action_name == "index" %>
        <%= link_to "ポートフォリオについて", root_path, class: "btn about-app-btn" %>
      <% end %>

      <% unless devise_controller? && hide_header_for_devise_page? %>
        <% if user_signed_in? %>
          <%= form_with url: destroy_user_session_path, method: :delete, local: true do %>
            <%= submit_tag "ログアウト", class: "btn" %>
          <% end %>
        <% else %>
          <%= link_to "ログイン", new_user_session_path, class: "btn btn-primary" %>
          <%= link_to "登録", new_user_registration_path, class: "btn btn-success" %>
        <% end %>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>